### ISSUE TITLE
Build fails due to uninitialized pointer warning  

### ISSUE THREAD

**Issue by vibhutisawant** [dstogov/llk#1]
@dstogov Below issue was found while building PHP from source on Big endian arch:

With --enable-werror flag enabled in configure command, following warning was observed while running the make command:

```
/root/php/php-src/ext/ffi/ffi_parser.c: In function 'get_skip_sym':
/root/php/php-src/ext/ffi/ffi_parser.c:1664:10: error: 'accept_pos' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   yy_pos = accept_pos;

```

Also raised a PR regarding the same ,[PR-5373](https://github.com/php/php-src/pull/5373)
As mentioned in the review comments:

> This change is moot, since ffi_parser.c is generated from ffi.g, so the change would likely have to be made at https://github.com/dstogov/llk/blob/70b057f49948a1f5bb37cc5cb1a324605c3903e3/llk_c.php#L262.

Could we have this code change implemented, to set *accespt_pos=NULL in order to fix listed warning?

**Comment by dstogov** [comment]
This warning is incorrect. It's probably caused by limitation of your C compiler. GCC 9.3 doesn't provide any warnings. "accept_pos" can't be uninitialized when "accept >= 0".

**Comment by vibhutisawant** [comment]
@dstogov Thanks for the quick response.

Tried building PHP using gcc 9.3.0, but it resulted in new warnings.However, the above warning didn't occur when tried using gcc 7.4.0. So it can be concluded that this behavior is mainly due to the compiler implementation.
